# Generated by Django 3.0.5 on 2020-04-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deal_findr', '0002_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('Choose Website', 'Choose Website'), ('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('Snapdeal', 'Snapdeal'), ('Myntra', 'Myntra')], default='Choose Website', max_length=14)),
                ('budget', models.DecimalField(decimal_places=3, max_digits=10)),
                ('productURL', models.URLField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Deals',
        ),
    ]
