# Generated by Django 3.0.5 on 2020-04-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal_findr', '0003_auto_20200418_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='productURL',
            field=models.URLField(max_length=2000),
        ),
    ]
